let shopItemsData = [
    {
      id: "ioytrhndcv",
      name: "Office Shirt",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "imagesFCC/img-2.png",
    },
    {
      id: "thyfhcbcv",
      name: "Mens Suit",
      price: 300,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "imagesFCC/img-4.png",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Mens Tie",
      price: 25,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "imagesFCC/img-5.png",
    },
    {
      id: "cbvxbcvsceldk",
      name: "denim shirt",
      price: 85,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "imagesFCC/img-9.png",
    },
    {
      id: "oiopijmjkhuihb",
      name: "denim pants",
      price: 120,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "imagesFCC/img-10.png",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "basic cap",
      price: 35,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "imagesFCC/img-11.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "leather boots",
      price: 350,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "imagesFCC/img-12.png",
    },
    {
        id: "sdafvasgvarsbaeb",
        name: "iPhone 13 Pro",
        price: 999,
        desc: "A flagship smartphone from Apple with advanced features.",
        img: "imagesFCC/iphone12.jpeg",
      },
      {
        id: "eedcEVCEGWGWCG",
        name: "Galaxy S21 Ultra",
        price: 1199,
        desc: "A premium Android smartphone with a high-resolution display and advanced camera system.",
        img: "imagesFCC/galaxy.jpeg",
      },
      {
        id: "GDVCGYDUCVCDCDCHNJS",
        name: "Pixel 6 Pro",
        price: 899,
        desc: "The latest Pixel smartphone with exceptional camera capabilities and seamless integration with Google services.",
        img: "imagesFCC/pixel.jpeg",
      },
      {
        id: "ACBHADCHADCBADCAD",
        name: "OnePlus 9 Pro",
        price: 899,
        desc: "A flagship killer smartphone with top-notch performance and a high-refresh-rate display.",
        img: "imagesFCC/oneplus.jpeg",
      },
      {
        id: "CBHJADBCADCBADC",
        name: "Mi 11 Ultra",
        price: 1099,
        desc: "A feature-packed smartphone with a large display, powerful processor, and high-resolution camera setup.",
        img: "imagesFCC/mi.jpeg",
      },
  ];